db:
  image: mongo:latest
  command: ["mongod", "--smallfiles"]
  volumes:
    - ./mongodata:/data/db
  ports:
    - "27017:27017"

api:
  build: ./api
  ports:
    - "8080:8080"
  links:
    - db

webfront:
  image: nginx:alpine
  volumes:
    - ./webfront/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./webfront/build:/www
  ports:
    - "9000:9000"

proxy:
  image: nginx:alpine
  volumes:
    - ./webcache/nginx.conf:/etc/nginx/nginx.conf:ro
  ports:
    - "80:80"
  links:
    - webfront
    - api
