db:
  image: mongo:latest
  command: ["mongod", "--smallfiles"]
  volumes:
    - ./mongodata:/data/db
  ports:
    - "8803:27017"

api:
  build: ./api
  environment:
    - CHANNEL_SECRET=d4a54c56a4711f297adc6f9e0eb1134d
    - CHANNEL_TOKEN=0pu52f1adC4VUlyXAnVVb3+dVoeFgEyS3yqXUzkfdw6tr4diek24GQAa2JNLPRFiH8b6vmHDVCTGqKrpB1DcqcVaDtGHj9cE5acil1LzUWxoSRsrkJxFgRu7XMtOGmiwOj6c8SsjvXvKWxN2r1aSigdB04t89/1O/w1cDnyilFU=
  ports:
    - "8802:8802"
  volumes:
    - ./api/config.json:/go/src/code.olipicus.com/bsd_shift_for_clean/api/config.json
  links:
    - db

webfront:
  image: nginx:alpine
  volumes:
    - ./webfront/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./webfront/build:/www
  ports:
    - "8801:8801"

proxy:
  image: nginx:alpine
  volumes:
    - /etc/letsencrypt/live/www.olipicus.com/fullchain.pem:/etc/nginx/ssl/server.crt:ro
    - /etc/letsencrypt/live/www.olipicus.com/privkey.pem:/etc/nginx/ssl/server.key:ro
    - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
  ports:
    - "443:443"
  links:
    - webfront
    - api
