db:
  image: mongo:latest
  command: ["mongod", "--smallfiles"]
  volumes:
    - ./mongodata:/data/db
  ports:
    - "8803:27017"

api:
  build: ./api
  ports:
    - "8802:8802"
  volumes:
    - ./api/config.json:/go/src/code.olipicus.com/bsd_shift_for_clean/api/config.json
  links:
    - db

webfront:
  image: nginx:alpine
  volumes:
    - ./webfront/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./webfront/build:/www
  ports:
    - "8801:8801"

proxy:
  image: nginx:alpine
  volumes:
    - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
  ports:
    - "8800:8800"
  links:
    - webfront
    - api
